//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlocArmario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public int IdContrato { get; set; }
        public System.DateTime Validade { get; set; }
        public string Valor { get; set; }
        public int IdArmario { get; set; }
        public int IdLocatario { get; set; }
    
        public virtual Armario Armario { get; set; }
        public virtual Locatario Locatario { get; set; }
    }
}
