//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlocArmario.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloDadosContainer : DbContext
    {
        public ModeloDadosContainer()
            : base("name=ModeloDadosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Locatario> Locatario { get; set; }
        public DbSet<Armario> Armario { get; set; }
        public DbSet<Contrato> Contrato { get; set; }
        public DbSet<Bloco> Bloco { get; set; }
        public DbSet<Secao> Secao { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
