//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlocArmario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secao
    {
        public Secao()
        {
            this.Bloco = new HashSet<Bloco>();
        }
    
        public int IdSecao { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Bloco> Bloco { get; set; }
    }
}
